### PR TITLE
Update from core 2015 03 02

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by kynan** [comment]
:+1:

**Comment by douglatornell** [comment]
I'm confused. This appears to be all of the commits ever from the bc repo version of the lesson plus a lot of commits from the new lesson-template repo, and GitHub says that there will be merge conflicts. So, what is this PR meant to accomplish?

**Comment by gvwilson** [comment]
Whoa - dunno what happened here, but you're right, there's way too much stuff.  I'll re-make.

**Comment by douglatornell** [comment]
Is it just that I need to pull and merge from upstream lesson-template? If so, I can easily do that.

**Comment by gvwilson** [comment]
I think you just need to pull/merge from the gh-pages branch of the 
lesson-template repo --- we've moved all the other stuff into 
lesson-example.

**Comment by douglatornell** [comment]
Pull/merge from the gh-pages branch of the lesson-template repo done in #6.

**Pull request closed without merging**
